export const GET_CANNED_RESPONSES = "GET_CANNED_RESPONSES";
export const ADD_CANNED_RESPONSE = "ADD_CANNED_RESPONSE";
export const DELETE_CANNED_RESPONSE = "DELETE_CANNED_RESPONSE";
export const EDIT_CANNED_RESPONSE = "EDIT_CANNED_RESPONSE";
export const BULK_ACTIVE_RESPONSE = "BULK_ACTIVE_RESPONSE";
export const BULK_DISABLE_RESPONSE = "BULK_DIABLE_RESPONSE";
export const BULK_DELETE_RESPONSE = "BULK_DELETE_RESPONSE";