export const GET_CANNED_RESPONSES = "GET_CANNED_RESPONSES";
export const ADD_CANNED_RESPONSE = "ADD_CANNED_RESPONSE";
export const DELETE_CANNED_RESPONSE = "DELETE_CANNED_RESPONSE";
export const TOGGLE_ADD_CANNED_BOX = "TOGGLE_ADD_CANNED_BOX";
export const EDIT_CANNED_RESPONSE = "EDIT_CANNED_RESPONSE";