export const GET_COMPANY_DATA = "GET_COMPANY_DATA";
export const ADD_NEW_COMPANY = "ADD_NEW_COMPANY";
export const EDIT_COMPANY_DETAILS = "EDIT_COMPANY_DETAILS";
export const DELETE_COMPANIES = "DELETE_COMPANIES";