export const GET_RAISED_TICKETS = "GET_RAISED_TICKETS";
export const GET_FORM_OPTIONS = "GET_FORM_OPTIONS";
export const RAISE_NEW_TICKET = "RAISE_NEW_TICKET";
export const SELECT_CURRENT_TICKET = "SELECT_CURRENT_TICKET";
export const GET_TICKET_MESSAGES = "GET_TICKET_MESSAGES";
export const ADD_TICKET_MESSAGE = "ADD_TICKET_MESSAGE";
