export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const TOGGLE_ADD_DEPARTMENT_BOX = "TOGGLE_ADD_DEPARTMENT_BOX";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";