export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const EDIT_DEPARTMENT = "EDIT_DEPARTMENT";
export const BULK_DELETE_DEPARTMENTS = "BULK_DELETE_DEPARTMENTS";
export const BULK_ACTIVE_DEPARTMENTS = "BULK_ACTIVE_DEPARTMENTS";
export const BULK_INACTIVE_DEPARTMENTS ="BULK_INACTIVE_DEPARTMENTS";