export const ADD_GENERAL_DETAILS = "ADD_GENERAL_DETAILS";
export const GET_GENERAL_DETAILS = "GET_GENERAL_DETAILS";
export const GET_LOCALIZATION_DETAILS = "GET_LOCALIZATION_DETAILS";
export const ADD_LOCALIZATION_DETAILS = "ADD_LOCALIZATION_DETAILS";
export const GET_CUSTOMER_PANEL_DETAILS = "GET_CUSTOMER_PANEL_DETAILS";
export const ADD_CUSTOMER_PANEL_DETAILS = "ADD_CUSTOMER_PANEL_DETAILS";