export const ADD_DATABASE_INFO = "ADD_DATABASE_INFO";
export const ADD_ADMIN_INFO = "ADD_ADMIN_INFO";
export const ADD_GENERAL_INFO = "ADD_GENERAL_INFO";
export const OPEN_PIN_MODAL = "OPEN_PIN_MODAL";
export const STEP_VALUE = "STEP_VALUE";