export const ADD_DATABASE_INFO = "ADD_DATABASE_INFO";
export const ADD_ADMIN_INFO = "ADD_ADMIN_INFO";
export const ADD_GENERAL_INFO = "ADD_GENERAL_INFO";
export const OPEN_PIN_MODAL = "OPEN_PIN_MODAL";
export const INCREMENT_STEPS = "INCREMENT_STEPS";
export const DECREMENT_STEPS = "DECREMENT_STEPS";
export const NULLIFY_PENDING_STEPS = "NULLIFY_PENDING_STEPS";
export const PIN_VERIFIED = "PIN_VERIFIED";