export const GET_SERVICES_LIST = "GET_SERVICES_LIST";
export const ADD_SERVICE = "ADD_SERVICE";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const BULK_ACTIVE_SERVICES = "BULK_ACTIVE_SERVICES";
export const BULK_DISABLE_SERVICES = "BULK_DISABLE_SERVICES";