export const GET_SUPPORT_STAFF = "GET_SUPPORT_STAFF";
export const ADD_SUPPORT_STAFF = "ADD_SUPPORT_STAFF";
export const DELETE_SUPPORT_STAFF = "DELETE_SUPPORT_STAFF";
export const EDIT_SUPPORT_STAFF = "EDIT_SUPPORT_STAFF";
export const GET_STAFF_ID = "GET_STAFF_ID";
export const BULK_DELETE_SUPPORT_STAFF = "BULK_DELETE_SUPPORT_STAFF";
export const DISABLE_STAFF_STATUS = "DISABLE_STAFF_STATUS";