export const GET_TICKET_STATUSES = "GET_TICKET_STATUSES";
export const ADD_TICKET_STATUS = "ADD_TICKET_STATUS";
export const DELETE_TICKET_STATUS = "DELETE_TICKET_STATUS";
export const EDIT_TICKET_STATUS = "EDIT_TICKET_STATUS";
export const BULK_ACTIVE_STATUS = "BULK_ACTIVE_STATUS";
export const BULK_DISABLE_STATUS = "BULK_DISABLE_STATUS";
export const BULK_DELETE_STATUS = "BULK_DELETE_STATUS";