export const GET_TICKET_STATUSES = "GET_TICKET_STATUSES";
export const ADD_TICKET_STATUS = "ADD_TICKET_STATUS";
export const DELETE_TICKET_STATUS = "DELETE_TICKET_STATUS";
export const EDIT_TICKET_STATUS = "EDIT_TICKET_STATUS";