export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKETS = "ADD_TICKETS";
export const GET_PRIORITIES = "GET_PRIORITIES";
export const SELECT_CURRENT_TICKET = "SELECT_CURRENT_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const BACK_TO_LIST = "BACK_TO_LIST";
export const DELETE_TICKET = "DELETE_TICKET";
export const GET_TICKET_ID = "GET_TICKET_ID";
