export const GET_TICKET_PRIORITIES = "GET_TICKET_PRIORITIES";
export const ADD_TICKET_PRIORITY = "ADD_TICKET_PRIORITY";
export const DELETE_TICKET_PRIORITY = "DELETE_TICKET_PRIORITY";
export const EDIT_TICKET_PRIORITY = "EDIT_TICKET_PRIORITY";
export const BULK_ACTIVE_PRIORITY = "BULK_ACTIVE_PRIORITY";
export const BULK_DISABLE_PRIORITY = "BULK_DISABLE_PRIORITY";
export const BULK_DELETE_PRIORITY = "BULK_DELETE_PRIORITY";