export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKETS = "ADD_TICKETS";
export const SELECT_CURRENT_TICKET = "SELECT_CURRENT_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const BACK_TO_LIST = "BACK_TO_LIST";
export const DELETE_TICKET = "DELETE_TICKET";
export const GET_TICKET_ID = "GET_TICKET_ID";
export const UPDATE_TICKET_STATUS = "UPDATE_TICKET_STATUS";
export const UPDATE_TICKET_PRIORITY = "UPDATE_TICKET_PRIORITY";
export const GET_CONVERSATION_LIST = "GET_CONVERSATION_LIST";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const GET_FORM_DETAILS = "GET_FORM_DETAILS";
export const ASSIGN_STAFF_TO_TICKET = "ASSIGN_STAFF_TO_TICKET";

