export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKETS = "ADD_TICKETS";
export const TOGGLE_ADD_TICKET_BOX = "SHOW_ADD_TICKET_BOX";
export const GET_PRIORITIES = "GET_PRIORITIES";
export const SELECT_CURRENT_TICKET = "SELECT_CURRENT_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";

