export const GET_TICKET_PRIORITIES = "GET_TICKET_PRIORITIES";
export const ADD_TICKET_PRIORITY = "ADD_TICKET_PRIORITY";
export const DELETE_TICKET_PRIORITY = "DELETE_TICKET_PRIORITY";
export const TOGGLE_ADD_PRIORITY_BOX = "TOGGLE_ADD_PRIORITY_BOX";